version: 0.2

phases:
  pre_build:
    commands:
      - npm install --silent --no-progress
      - cd $CODEBUILD_SRC_DIR/services/cdn && npm install --silent --no-progress
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - npm run test
      - mkdir -p target/dev
      - mkdir target/prod
      - npm run package-all
artifacts:
  files:
    - services/**/target/**/*
    - services/**/serverless.yml
    - services/*/package.json
    - package.json
    - deploy.sh
