version: 0.2

phases:
  install:
    commands:
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
      - npm install --silent --no-progress
  build:
    commands:
      - echo "Build - not yet implemented..."

artifacts:
  files:
    - target/**/*
    - serverless.yml
    - deploy.sh
