service: lahiyam-website-storage

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  stage: dev
  region: us-east-1

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        # Set the CORS policy
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
    ReactDeploymentBucket:
      Type: AWS::S3::Bucket
      Properties:
        WebsiteConfiguration:
          IndexDocument: index.html
    # CloudFront
    ReactCFDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: !GetAtt ReactDeploymentBucket.DomainName
              Id: !Ref ReactDeploymentBucket
              S3OriginConfig:
                OriginIdentityAccess: ""
          DefaultRootObject: index.html
          Enabled: true
          DefaultCacheBehavior:
            MinTTL: 86400 # 1 day
            MaxTTL: 2592000 # 30 days
            ForwardedValues:
              QueryString: true
            TargetOriginId: !Ref ReactDeploymentBucket
            ViewerProtocolPolicy: "redirect-to-https"

  # Print out the name of the bucket that is created
  Outputs:
    LahiyamBucketArn:
      Value:
        Fn::GetAtt:
          - S3Bucket
          - Arn
      Export:
        Name: ${self:custom.stage}-LahiyamBucketArn

    ReactDeploymentBucketArn:
      Value:
        Fn::GetAtt:
          - ReactDeploymentBucket
          - Arn
      Export:
        Name: ${self:custom.stage}-ReactDeploymentBucketArn

    ReactCFDistributionArn:
      Value:
        Fn::GetAtt:
          - ReactCFDistribution
          - Arn
      Export:
        Name: ${self:custom.stage}-ReactCFDistributionArn

    LahiyamBucketName:
      Value:
        Ref: S3Bucket
      Export:
        Name: ${self:custom.stage}-LahiyamBucket

    ReactDeploymentBucketName:
      Value:
        Ref: ReactDeploymentBucket
      Export:
        Name: ${self:custom.stage}-ReactDeploymentBucket

    ReactCFDistributionName:
      Value:
        Ref: ReactCFDistribution
      Export:
        Name: ${self:custom.stage}-ReactCFDistribution
